version: '3.7'

services:
  web:
    container_name: dev_backend
    build: .
    restart: always
    command: python api/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgres_dev
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "8967:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
