version: '3.7'

services:
  web:
    container_name: dev_backend
    build: .
    restart: always
    environment:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
